app:
  name: details
environment:
  value: development
http:
  mode: release
  port: 8081
db:
  url: root:zhanghu123@tcp(127.0.0.1:3306)/products?charset=utf8&parseTime=True&loc=Local
  debug: false
conf:
  db: /Users/gaozhanghu/Documents/hz_project/internal/pkg/conf
log:
  filename: /tmp/details.log
  maxSize: 500
  maxBackups: 3
  maxAge: 3
  level: "debug"
  stdout: false
consul:
  addr: localhost:8500
grpc:
  port: 0
jaeger:
  serviceName: details
  reporter:
    localAgentHostPort: "jaeger-agent:6831"
  sampler:
    type: const
    param: 1
